In [ ]:
import numpy as np

In [ ]:
X1=np.array([3,1,2,4,3])
X2=np.array([6,3,4,7,5])
y=np.array([1,0,0,1,1])

In [ ]:
X=np.column_stack((np.ones(5),X1,X2))

In [ ]:
B=np.linalg.inv(X.T @ X) @ X.T @ y

In [ ]:
b0,b1,b2= B

In [ ]:
print("the value of (b0) is", b0)
print("the value of (b1) is", b1)
print("the value of (b2)is", b2)

the value of (b0) is -0.5999999999999837
the value of (b1) is 0.3333333333333277
the value of (b2)is 0.06666666666666865


In [ ]:
import math
def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [ ]:
#step 1: clculate linear combination(z=b0+b1*x2)
z = X @ B
print("\n Linear combination (z):")
print(z)


 Linear combination (z):
[ 0.8        -0.06666667  0.33333333  1.2         0.73333333]


In [ ]:
#s2= apply sigmoid to get probabilities
y_prob = np.array([sigmoid(val) for val in z])
print("\n predicted probabilities (sigmoid output):")
print(y_prob)


 predicted probabilities (sigmoid output):
[0.68997448 0.4833395  0.58257021 0.76852478 0.67553632]


In [ ]:
#s3 = convert probabilities into class labels
y_pred = (y_prob >=0.5).astype(int)
print("\n predicted classes")
print(y_pred)


 predicted classes
[1 0 1 1 1]


In [ ]:
#confusion matrix components
TP = np.sum((y == 1) & (y_pred == 1))
TN = np.sum((y == 0) & (y_pred == 0))
FP = np.sum((y == 0) & (y_pred == 1))
FN = np.sum((y == 1) & (y_pred == 0))

In [ ]:
print("\n confusion matrix:")
print(f"TP + {TP}, FP = {FP}")
print(f"FN + {FN}, TN = {TN}")



 confusion matrix:
TP + 3, FP = 1
FN + 0, TN = 1


In [ ]:
#accuracy
accuracy = (TP + TN) / len(y)
#precision
precision = TP / (TP + FP) if (TP + FP) != 0 else 0
#recall
recall = TP / (TP + FN) if (TP + FN) != 0 else 0
#f1 score
f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) != 0 else 0

In [ ]:
print("\n classification metrics:")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1_score:.4f}")


 classification metrics:
Accuracy: 0.8000
Precision: 0.7500
Recall: 1.0000
F1 Score: 0.8571
